let adjective = [
  "3000 BC",
  "Ancient",
  "Arcadian",
  "Bacon Wrapped",
  "Baleful",
  "Bi-Polar",
  "Bittersweet",
  "Black & White",
  "Blind",
  "Broken",
  "Canned",
  "Caustic",
  "Cerulean",
  "Chinese",
  "Classic",
  "Cloudy",
  "Corrupt",
  "Crabby",
  "Crunchy",
  "Deep Fried",
  "Diabolical",
  "Diamond Encrusted",
  "Didactic",
  "Digital",
  "Discombobulated",
  "Disgruntled",
  "Eccentric",
  "Equestrian",
  "Erroneous",
  "Extra Spicy",
  "Fake",
  "Fancy",
  "Fastidious",
  "Fictitious",
  "Gargantuan",
  "Glittering",
  "Glitchy",
  "Glowing",
  "Gluten-Free",
  "Gold-Plated",
  "Happy",
  "Hollowed Out",
  "Icelandic",
  "Imaginary",
  "Impulsive",
  "Incendiary",
  "Insidious",
  "Intoxicated",
  "Inquisitive",
  "Jocular",
  "Lachrymose",
  "Lackadaisical",
  "Long-Necked",
  "Luminous",
  "Macrosmatic",
  "Meat Eating",
  "Mechanical",
  "Moo Shu",
  "Nefarious",
  "Neolithic",
  "New York",
  "One-Armed",
  "One-Eyed",
  "One-Legged",
  "Oxidized",
  "Parched",
  "Peruvian",
  "Petrified",
  "Poetic",
  "Prickly",
  "Prophetic",
  "Pungent",
  "Quiescent",
  "Rabid",
  "Rubberized",
  "Saffron",
  "Saucy",
  "Sleepy",
  "Solitary",
  "Spasmodic",
  "Stir-Fried",
  "Striped",
  "Sweet & Sour",
  "Talkative",
  "Teal",
  "Tenacious",
  "Tiny",
  "Translucent",
  "Turbulent",
  "Ubiquitous",
  "Unorthodox",
  "Verdant",
  "Vintage",
  "Voracious",
  "Warped",
  "Wise",
  "Withering",
  "Wooden",
  "X-Rated",
  "Zealous",
];
let noun = [
  "Anteater",
  "Avocado",
  "Ballerina",
  "Beetle",
  "Boulder",
  "Botanist",
  "Brain Surgeon",
  "Butterfly",
  "Cactus",
  "Cacophony",
  "Chainsaw",
  "Chandelier",
  "Cheese Head",
  "Cowboy",
  "Cucumber",
  "Data Cruncher",
  "Dragonfly",
  "Earthling",
  "Egret",
  "Eggplant",
  "Eyeball",
  "Explosion",
  "Fish",
  "Flu",
  "Foot",
  "Hipster",
  "Hullaballoo",
  "Insomniac",
  "Jellyfish",
  "Gibberish",
  "Giraffe",
  "Grasshopper",
  "Grilled Tomatoe",
  "Hippo",
  "Lamp Post",
  "Lizard",
  "Lobster",
  "Man",
  "Meatball",
  "Muckmoo",
  "Mudskipper",
  "New Yorker",
  "Night Heron",
  "Nut Job",
  "Obelus",
  "Octopus",
  "Penguin",
  "Pineapple",
  "Platypus",
  "Pole Jumper",
  "Politician",
  "Poppycock",
  "Pseudoscientist",
  "Rabbit",
  "Roadrunner",
  "Rodent",
  "Rooster",
  "Salamander",
  "Screwdriver",
  "Skyscraper",
  "SPAM Sandwich",
  "Sonata",
  "Starfish",
  "Sunflower",
  "Superman",
  "T-Rex",
  "Triangle",
  "Turtle",
  "UFO",
  "Unicorn",
  "Vegetarian",
  "Volkswagon",
  "Video",
  "Warbler",
  "Watermellon",
  "Woman",
  "Wood Duck",
  "Woodpecker",
  "Whippersnapper",
  "Wyvern",
  "Zebra",
];

let verb = [
  "Acting",
  "Apologizing",
  "Bending",
  "Billowing",
  "Broadcasting",
  "Burning",
  "Counts",
  "Cries",
  "Cut",
  "Disected",
  "Dreams",
  "Electrified",
  "Erased",
  "Examined",
  "Flattened",
  "Flip-Flopped",
  "Flew",
  "Frozen",
  "Growing",
  "Halucinates",
  "Improvising",
  "Incinerated",
  "Meditating",
  "Minced",
  "Pan Fried",
  "Pillaging",
  "Ponders",
  "Rotating",
  "Running",
  "Screaming",
  "Screams",
  "Sleeping",
  "Sleeps",
  "Smothered",
  "Spinning",
  "Squished",
  "Stretched",
  "Superglued",
  "Swerves",
  "Twisting",
  "Weeps",
];

let adverb = [
  "Acutely",
  "All Night Long",
  "After Sunset",
  "After Midnight",
  "Again",
  "Asymetrically",
  "At 3:02AM",
  "Badly",
  "Backwards",
  "Before Sunday",
  "Before Sunrise",
  "Before Sunset",
  "Bi-Weekly",
  "Counter-Clockwise",
  "Daily",
  "Down Under",
  "Eastbound",
  "Efficiently",
  "Fast-Forward",
  "Fastly",
  "For 7 Days",
  "Frequently",
  "Fully Awake",
  "Grudigingly",
  "Hardly Ever",
  "Hourly",
  "In 3rd Gear",
  "In Bees Wax",
  "In Butter",
  "In Hyperbole",
  "In Reverse",
  "In The Shade",
  "Inside-Out",
  "Incognito",
  "Indefinitely",
  "Jaggedly",
  "Lengthwise",
  "Like Toast",
  "Like A Hot Tamale",
  "Like Winter",
  "Loudly",
  "Naked",
  "Nearby",
  "Now",
  "Oddly",
  "Off Broadway",
  "On The Uptown F-Train",
  "On A Yoga Mat",
  "On 5th Avenue",
  "On Hollywood Blvd.",
  "On The Ceiling",
  "Once",
  "Overhead",
  "Overseas",
  "Periodically",
  "Quietly",
  "Quickly",
  "Quizzically",
  "Realistically",
  "Retroactively",
  "Sarcastically",
  "Sideways",
  "Silently",
  "Slowly",
  "Softly",
  "Sometimes",
  "Southern Style",
  "Sporadically",
  "Strangely",
  "Straight",
  "Systematically",
  "Szechuan Style",
  "Towards The Sun",
  "Twice",
  "Underwater",
  "Until Friday",
  "Unfrequently",
  "Upside-Down",
  "Vertically",
  "When Broken",
  "Wildly",
  "Without Remorse",
];
