let adjective = [
  "3000 BC",
  "Ancient",
  "Arcadian",
  "Bacon Wrapped",
  "Bi-Polar",
  "Bittersweet",
  "Black & White",
  "Blind",
  "Broken",
  "Canned",
  "Caustic",
  "Cerulean",
  "Classic",
  "Cloudy",
  "Corrupt",
  "Crabby",
  "Crunchy",
  "Deep Fried",
  "Diabolical",
  "Diamond Encrusted",
  "Didactic",
  "Digital",
  "Discombobulated",
  "Disgruntled",
  "Eccentric",
  "Equestrian",
  "Erroneous",
  "Euphoric",
  "Extra Spicy",
  "Fake",
  "Fancy",
  "Fastidious",
  "Fictitious",
  "Freeze-Dried",
  "Gargantuan",
  "Glittering",
  "Glitchy",
  "Glowing",
  "Gluten-Free",
  "Gold-Plated",
  "Happy",
  "Hollowed Out",
  "Icelandic",
  "Imaginary",
  "Impulsive",
  "Incendiary",
  "Insidious",
  "Intoxicated",
  "Inquisitive",
  "Lachrymose",
  "Lackadaisical",
  "Long-Necked",
  "Luminous",
  "Macrosmatic",
  "Meat Eating",
  "Mechanical",
  "Moo Shu",
  "Nefarious",
  "Neolithic",
  "New York",
  "Obtuse",
  "One-Armed",
  "One-Eyed",
  "One-Legged",
  "Oxidized",
  "Parched",
  "Peruvian",
  "Petrified",
  "Poetic",
  "Prickly",
  "Prophetic",
  "Pungent",
  "Quiescent",
  "Rabid",
  "Rubberized",
  "Saffron",
  "Saucy",
  "Sleepy",
  "Solitary",
  "Spasmodic",
  "Stir-Fried",
  "Striped",
  "Sweet & Sour",
  "Talkative",
  "Teal",
  "Tenacious",
  "Tiny",
  "Translucent",
  "Turbulent",
  "Ubiquitous",
  "Unorthodox",
  "Verdant",
  "Vegan",
  "Vintage",
  "Voracious",
  "Warped",
  "Wise",
  "Withering",
  "Wooden",
  "X-Rated",
  "Zealous",
];
let noun = [
  "Anteater",
  "Avocado",
  "Ballerina",
  "Beetle",
  "Boulder",
  "Botanist",
  "Butterfly",
  "Cactus",
  "Cacophony",
  "Chainsaw",
  "Chandelier",
  "Cheese Head",
  "Cowboy",
  "Cucumber",
  "Data Cruncher",
  "Dragonfly",
  "Earthling",
  "Egret",
  "Eggplant",
  "Eyeball",
  "Explosion",
  "Fish",
  "Flu",
  "Foot",
  "Hipster",
  "Hullaballoo",
  "Insomniac",
  "Jellyfish",
  "Gecko",
  "Gibberish",
  "Giraffe",
  "Grasshopper",
  "Tomatoe",
  "Hippo",
  "Labotomist",
  "Lamp Post",
  "Lobster",
  "Meatball",
  "Muckmoo",
  "Mudskipper",
  "New Yorker",
  "Night Heron",
  "Nut Job",
  "Obelus",
  "Octopus",
  "Penguin",
  "Phrenologist",
  "Pineapple",
  "Platypus",
  "Pole Jumper",
  "Politician",
  "Poppycock",
  "Pseudoscientist",
  "Rabbit",
  "Roadrunner",
  "Rodent",
  "Rooster",
  "Salamander",
  "Screwdriver",
  "Skyscraper",
  "SPAM Sandwich",
  "Sonata",
  "Starfish",
  "Sunflower",
  "Superman",
  "T-Rex",
  "Triangle",
  "Turtle",
  "UFO",
  "Unicorn",
  "Vegetarian",
  "Volkswagon",
  "Video",
  "Warbler",
  "Watermellon",
  "Wood Duck",
  "Woodpecker",
  "Whippersnapper",
  "Wyvern",
  "Zebra",
];

let verb = [
  "Acting",
  "Apologizing",
  "Bending",
  "Billowing",
  "Broadcasting",
  "Burning",
  "Counts",
  "Cries",
  "Cut",
  "Dissected",
  "Dreams",
  "Electrified",
  "Erased",
  "Examined",
  "Flattened",
  "Flip-Flopped",
  "Flew",
  "Frozen",
  "Growing",
  "Halucinates",
  "Improvising",
  "Incinerated",
  "Meditating",
  "Minced",
  "Pan Fried",
  "Pillaging",
  "Ponders",
  "Preserved",
  "Recycled",
  "Rotating",
  "Running",
  "Screaming",
  "Sleeping",
  "Sliced",
  "Smothered",
  "Spinning",
  "Squished",
  "Stretched",
  "Superglued",
  "Swerves",
  "Smims",
  "Twittering",
  "Weeps",
];

let adverb = [
  "Acutely",
  "All Night Long",
  "After Sunset",
  "After Midnight",
  "Again",
  "Asymetrically",
  "At 3:02AM",
  "Badly",
  "Backwards",
  "Before Lunch",
  "Before Sunrise",
  "Before Sunset",
  "Bi-Weekly",
  "Counter-Clockwise",
  "Daily",
  "Down Under",
  "Down 5th Avenue",
  "Eastbound",
  "Efficiently",
  "Fast-Forward",
  "Fastly",
  "For 7 Days",
  "Frequently",
  "Fully Awake",
  "Grudigingly",
  "Hardly Ever",
  "Hourly",
  "In 3rd Gear",
  "In Bees Wax",
  "In Butter",
  "In Hyperbole",
  "In Reverse",
  "In Central Park",
  "Inside-Out",
  "Incognito",
  "Infinitely Large",
  "Jaggedly Straight",
  "Lengthwise",
  "Like Avocadoe Toast",
  "Like A Hot Tamale",
  "Like Vodka",
  "Loudly",
  "Naked",
  "Nearby",
  "Now",
  "Oddly",
  "Off-Broadway",
  "On The Uptown F-Train",
  "On A Yoga Mat",
  "On Hollywood Blvd.",
  "On The Ceiling",
  "Once",
  "Overhead",
  "Overseas",
  "Perpendicular",
  "Periodically",
  "Quietly",
  "Quickly",
  "Quizzically",
  "Realistically",
  "Retroactively",
  "Sarcastically",
  "Sideways",
  "Silently",
  "Slowly",
  "Softly",
  "Sometimes",
  "Southern Style",
  "Sporadically",
  "Strangely",
  "Straight to Venus",
  "Systematically",
  "Szechuan Style",
  "Towards The Sun",
  "Twice on Monday",
  "Underwater",
  "Until Friday",
  "Unfrequently",
  "Upside-Down",
  "Vertically",
  "When Broken",
  "Wildly",
  "Without Remorse",
];
