let adjective = [
  "Arcadian",
  "Bacon Flavored",
  "Baleful",
  "Bittersweet",
  "Black & White",
  "Blind",
  "Bronze",
  "Caustic",
  "Cerulean",
  "Classic",
  "Cloudy",
  "Corrupt",
  "Crabby",
  "Crunchy",
  "Diabolical",
  "Didactic",
  "Digital",
  "Discombobulated",
  "Disgruntled",
  "Equestrian",
  "Erroneous",
  "Extra Spicy",
  "Fake",
  "Fastidious",
  "Fictitious",
  "Gargantuan",
  "Glittering",
  "Glitchy",
  "Glowing",
  "Gold-Plated",
  "Happy",
  "Icelandic",
  "Imaginary",
  "Incendiary",
  "Insidious",
  "Intoxicated",
  "Inquisitive",
  "Jocular",
  "Lachrymose",
  "Lackadaisical",
  "Luminous",
  "Macrosmatic",
  "Mechanical",
  "Nefarious",
  "New York",
  "One-Armed",
  "Oxidized",
  "Parsimonious",
  "Peruvian",
  "Petrified",
  "Poetic",
  "Prickly",
  "Prophetic",
  "Quiescent",
  "Rabid",
  "Rubberized",
  "Saffron",
  "Saucy",
  "Serpentine",
  "Solitary",
  "Spasmodic",
  "Zebra Striped",
  "Talking",
  "Teal",
  "Tenacious",
  "Tiny",
  "Translucent",
  "Turbulent",
  "Ubiquitous",
  "Unorthodox",
  "Verdant",
  "Vintage",
  "Voracious",
  "Wise",
  "Withering",
  "Wooden",
  "X-Rated",
  "Zealous",
];
let noun = [
  "Anteater",
  "Avocado",
  "Beetle",
  "Boulder",
  "Butterfly",
  "Cacophony",
  "Chainsaw",
  "Chandelier",
  "Chuckwalla",
  "Cucumber",
  "Dancer",
  "Data",
  "Dragonfly",
  "Duck",
  "Egret",
  "Eyeball",
  "Explosion",
  "Fish",
  "Flu",
  "Foot",
  "Hip Hop",
  "Hullaballoo",
  "Gibberish",
  "Grasshopper",
  "Grilled Tomatoe",
  "Hippo",
  "Lamp Post",
  "Man",
  "Meatball",
  "Mudskipper",
  "New Yorker",
  "Night Heron",
  "Nut Job",
  "Obelus",
  "Octopus",
  "Politician",
  "Poppycock",
  "Pseudoscience",
  "Rabbit",
  "Roadrunner",
  "Rodent",
  "Rooster",
  "Salamander",
  "Screwdriver",
  "Skyscraper",
  "Sonata",
  "Spam",
  "Sunflower",
  "Superman",
  "T-Rex",
  "Triangle",
  "Turtle",
  "UFO",
  "Unicorn",
  "Vegetarian",
  "Volkswagon",
  "Video",
  "Warbler",
  "Watermellon",
  "Woman",
  "Woodpecker",
  "Whippersnapper",
  "Wyvern",
  "Zoanthropy",
];

let verb = [
  "Acting",
  "Apologizing",
  "Bending",
  "Billowing",
  "Broadcasting",
  "Burning",
  "Counts",
  "Cries",
  "Cut",
  "Dreams",
  "Electrified",
  "Erased",
  "Examined",
  "Flattened",
  "Flew",
  "Frozen",
  "Growing",
  "Halucinates",
  "Improvising",
  "Meditating",
  "Pan Fried",
  "Pillaging",
  "Ponders",
  "Rotating",
  "Running",
  "Screaming",
  "Screams",
  "Sleeping",
  "Sleeps",
  "Spinning",
  "Squished",
  "Stretched",
  "Superglued",
  "Twisting",
  "Weeps",
];

let adverb = [
  "Acutely",
  "All Night Long",
  "After Sunset",
  "After Midnight",
  "Again",
  "Asymetrically",
  "At 3AM",
  "Badly",
  "Backwards",
  "Before Sunrise",
  "Before Sunset",
  "Bi-Weekly",
  "Counter-Clockwise",
  "Daily",
  "Down Under",
  "Eastbound",
  "Efficiently",
  "Fast",
  "Fastly",
  "Frequently",
  "Grudigingly",
  "Hard",
  "Hardly",
  "Hourly",
  "In 3rd Gear",
  "In Reverse",
  "Inside-Out",
  "Incognito",
  "Indefinitely",
  "Jaggedly",
  "Lengthwise",
  "Like A Bag of Hammers",
  "Like Burnt Toast",
  "Like It's 1999",
  "Like A Hot Tamale",
  "Loudly",
  "Naked",
  "Nearby",
  "Now",
  "Oddly",
  "Once",
  "Overhead",
  "Overseas",
  "Periodically",
  "Quickly",
  "Quizzically",
  "Realistically",
  "Sarcastically",
  "Sideways",
  "Silently",
  "Slowly",
  "Softly",
  "Sometimes",
  "Southern Style",
  "Sporadically",
  "Still",
  "Strangely",
  "Straight",
  "Systematically",
  "Together",
  "Towards Yesterday",
  "Twice",
  "Underwater",
  "Until Friday",
  "Unfrequently",
  "Upside-Down",
  "Vertically",
  "Well",
  "Wildly",
  "Without Remorse",
];
